// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqNBSu-sxTAKdvFEhbdccSmnwUQnOxmjU',
    appId: '1:1063139514633:web:48cd8789570aee47235bd8',
    messagingSenderId: '1063139514633',
    projectId: 'bookappstore-a3e61',
    authDomain: 'bookappstore-a3e61.firebaseapp.com',
    storageBucket: 'bookappstore-a3e61.firebasestorage.app',
    measurementId: 'G-FSN0EESX7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCAn0crFBFLDqjc0VNeFSo-VoJmdgJBQk',
    appId: '1:1063139514633:android:ef489248d498344d235bd8',
    messagingSenderId: '1063139514633',
    projectId: 'bookappstore-a3e61',
    storageBucket: 'bookappstore-a3e61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALNbsOoh-eyS_tfIReAtaKBv39_VMK0zo',
    appId: '1:1063139514633:ios:44aa2149f0a00152235bd8',
    messagingSenderId: '1063139514633',
    projectId: 'bookappstore-a3e61',
    storageBucket: 'bookappstore-a3e61.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqNBSu-sxTAKdvFEhbdccSmnwUQnOxmjU',
    appId: '1:1063139514633:web:191e63bc7ba5c185235bd8',
    messagingSenderId: '1063139514633',
    projectId: 'bookappstore-a3e61',
    authDomain: 'bookappstore-a3e61.firebaseapp.com',
    storageBucket: 'bookappstore-a3e61.firebasestorage.app',
    measurementId: 'G-R1M495CZYE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALNbsOoh-eyS_tfIReAtaKBv39_VMK0zo',
    appId: '1:1063139514633:ios:44aa2149f0a00152235bd8',
    messagingSenderId: '1063139514633',
    projectId: 'bookappstore-a3e61',
    storageBucket: 'bookappstore-a3e61.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

}