// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkeymHpjUUrsx7ANoLuAqsocIigrb4Is0',
    appId: '1:545586718329:web:942f61a57ef20d79c9d6a8',
    messagingSenderId: '545586718329',
    projectId: 'fws16-a1ebd',
    authDomain: 'fws16-a1ebd.firebaseapp.com',
    storageBucket: 'fws16-a1ebd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcos0TxP7LBfdKFgbB61NirYHMTcU0QCg',
    appId: '1:545586718329:android:19e453916576785bc9d6a8',
    messagingSenderId: '545586718329',
    projectId: 'fws16-a1ebd',
    storageBucket: 'fws16-a1ebd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBtyd--jeTESECrcL43aAJuwUtB1kEMTw',
    appId: '1:545586718329:ios:bde7cdd810761c7bc9d6a8',
    messagingSenderId: '545586718329',
    projectId: 'fws16-a1ebd',
    storageBucket: 'fws16-a1ebd.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkeymHpjUUrsx7ANoLuAqsocIigrb4Is0',
    appId: '1:545586718329:web:8a474077c393a230c9d6a8',
    messagingSenderId: '545586718329',
    projectId: 'fws16-a1ebd',
    authDomain: 'fws16-a1ebd.firebaseapp.com',
    storageBucket: 'fws16-a1ebd.firebasestorage.app',
  );

}